// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHotel.EntityFrameworkCore;

namespace MyHotel.Migrations
{
    [DbContext(typeof(MyHotelDbContext))]
    [Migration("20190803175002_RoomDetails")]
    partial class RoomDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyHotel.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime>("RegisterDate");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alper Ebicoglu",
                            RegisterDate = new DateTime(2019, 7, 24, 19, 50, 2, 480, DateTimeKind.Local).AddTicks(1311)
                        },
                        new
                        {
                            Id = 2,
                            Name = "George Michael",
                            RegisterDate = new DateTime(2019, 7, 29, 19, 50, 2, 481, DateTimeKind.Local).AddTicks(9390)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Daft Punk",
                            RegisterDate = new DateTime(2019, 8, 2, 19, 50, 2, 481, DateTimeKind.Local).AddTicks(9565)
                        });
                });

            modelBuilder.Entity("MyHotel.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckinDate");

                    b.Property<DateTime>("CheckoutDate");

                    b.Property<int>("GuestId");

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckinDate = new DateTime(2019, 8, 1, 19, 50, 2, 482, DateTimeKind.Local).AddTicks(3414),
                            CheckoutDate = new DateTime(2019, 8, 6, 19, 50, 2, 482, DateTimeKind.Local).AddTicks(3423),
                            GuestId = 1,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 2,
                            CheckinDate = new DateTime(2019, 8, 2, 19, 50, 2, 482, DateTimeKind.Local).AddTicks(5052),
                            CheckoutDate = new DateTime(2019, 8, 7, 19, 50, 2, 482, DateTimeKind.Local).AddTicks(5059),
                            GuestId = 2,
                            RoomId = 4
                        });
                });

            modelBuilder.Entity("MyHotel.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowedSmoking");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<int>("Number");

                    b.Property<int?>("RoomDetailId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("RoomDetailId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedSmoking = false,
                            Name = "yellow-room",
                            Number = 101,
                            RoomDetailId = 100,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AllowedSmoking = false,
                            Name = "blue-room",
                            Number = 102,
                            RoomDetailId = 101,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AllowedSmoking = false,
                            Name = "white-room",
                            Number = 103,
                            RoomDetailId = 102,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AllowedSmoking = false,
                            Name = "black-room",
                            Number = 104,
                            RoomDetailId = 103,
                            Status = 0
                        });
                });

            modelBuilder.Entity("MyHotel.Entities.RoomDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Beds");

                    b.Property<int>("Windows");

                    b.HasKey("Id");

                    b.ToTable("RoomDetails");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Beds = 1,
                            Windows = 2
                        },
                        new
                        {
                            Id = 101,
                            Beds = 1,
                            Windows = 4
                        },
                        new
                        {
                            Id = 102,
                            Beds = 2,
                            Windows = 3
                        },
                        new
                        {
                            Id = 103,
                            Beds = 2,
                            Windows = 0
                        });
                });

            modelBuilder.Entity("MyHotel.Entities.Reservation", b =>
                {
                    b.HasOne("MyHotel.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyHotel.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyHotel.Entities.Room", b =>
                {
                    b.HasOne("MyHotel.Entities.RoomDetail", "RoomDetail")
                        .WithMany()
                        .HasForeignKey("RoomDetailId");
                });
#pragma warning restore 612, 618
        }
    }
}
